[package]
name = "launch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ds323x = "0.5.1"
mpu9250-i2c = "0.6.8"
rppal = { version = "0.15.0", features = ["hal"] }
ublox = "0.4.4"
