name: Generate Documentation

on:
  push:
    branches: [ "main", "Radio", "DSP"  ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update
        run: sudo apt update

      - name: Install soapysdr
        run: sudo apt install -y libsoapysdr-dev

      - name: Build docs
        run: cargo doc --no-deps

      - name: Clone Repo
        run: |
          git clone git@github.com:purdue-orbital/OrbitalCommand.git
          cd OrbitalCommand
          git checkout docs

      - name: Move docs
        run: mv target/doc OrbitalCommand/docs

      - name: Push to Branch
        env:
          GH_TOKEN: ${{ secrets.KEY }}
        run: |
          cd OrbitalCommand
          git config --global user.name "Bot"
          git config --global user.email "Nicholas-Ball@users.noreply.github.com"
          git add .
          git commit -m "Updating Doc"
          git remote set-url origin ${GH_TOKEN_ORG}@github.com:purdue-orbital/OrbitalCommand.git
          git push