name: Radio Tests

on:
  push:
    branches: [ "main", "Radio", "DSP"  ]
  pull_request:
    branches: [ "main", "Radio", "DSP"  ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install soapysdr
        run: sudo apt install -y libsoapysdr-dev

      - name: Run tests
        run: cargo test --verbose -p radio